import Head from "next/head";
// import Image from "next/image";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({
  subsets: ["latin", "latin-ext"],
  variable: "--dm-sans",
});

import HomePage from "@/views/HomePage";
import Script from "next/script";
export default function Home() {
  return (
    <>
      <Head>
        <title>OSN Image Tagger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={dmSans.variable}>
        <HomePage />
      </main>
    </>
  );
}
